services:
  - type: web
    name: justicai
    env: docker
    plan: free
    # ipAllowList satırı kaldırıldı, hata sebebi buydu.
    envVars:
      - key: OPENAI_API_KEY
        sync: false # Bunu Render panelinden elle gireceksin
      - key: FLASK_SECRET
        generateValue: true